CREATE VIEW ORDER_XFRM.v_order_detail AS
SELECT
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    ITEM_ID,
    QTY,
    TOTAL_AMOUNT,
    CREATE_DATE AS DETAIL_CREATE_DATE,
    CREATE_USER AS DETAIL_CREATE_USER
FROM
    ORDER_BASE.ORDER_DETAIL;