CREATE OR REPLACE VIEW ORDER_XFRM.v_order_header AS
SELECT
    ORDER_ID,
    ORDER_DATE,
    STATUS,
    CUSTOMER_ID,
    ITEM_COUNT,
    TOTAL_AMOUNT,
    DISCOUNT,
    CREATE_DATE AS ORDER_CREATE_DATE,
    CREATE_USER AS ORDER_CREATE_USER,
    COUPON_CODE
FROM
    ORDER_BASE.ORDER_HEADER;