CREATE VIEW ORDER_XFRM.v_customer AS
SELECT
    CUSTOMER_ID,
    ADDRESS,
    PHONE_NO,
    STATUS AS CUSTOMER_STATUS,
    CATEGORY AS CUSTOMER_CATEGORY,
    TOTAL_ORDERS,
    TOTAL_INVOICE_AMOUNT,
    LOYALTY_POINTS,
    CREATE_DATE AS CUSTOMER_CREATE_DATE,
    CREATE_USER AS CUSTOMER_CREATE_USER
FROM
    ORDER_BASE.CUSTOMER;