create table ORDER_BASE.ORDER_HEADER (
    ORDER_ID VARCHAR(10) UNIQUE,
    ORDER_DATE DATE,
    STATUS VARCHAR(10),
    CUSTOMER_ID VARCHAR(10),
    ITEM_COUNT INTEGER,
    TOTAL_AMOUNT NUMERIC(12,2),
    DISCOUNT NUMERIC(10,2),
    CREATE_DATE DATE,
    CREATE_USER VARCHAR(10),
    COUPON_CODE VARCHAR(10)
);