CREATE TABLE INTEL_ASSESMENT."ORDER_BASE".ORDER_DETAIL (
    ORDER_ID VARCHAR(10),
    ORDER_DATE DATE,
    CUSTOMER_ID VARCHAR(10),
    ITEM_ID VARCHAR(10),
    QTY INTEGER,
    TOTAL_AMOUNT NUMERIC(12,2),
    CREATE_DATE DATE,
    CREATE_USER VARCHAR(10),
    PRICE NUMERIC(12,2),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER_HEADER(ORDER_ID)
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);