CREATE TABLE INTEL_ASSESMENT."ORDER_BASE".PROMOTION (
    PROMOTION_ID VARCHAR(10),
    CUSTOMER_CATEGORY VARCHAR(10),
    PROMOTION_TYPE VARCHAR(10),
    PROMOTION_VALUE  NUMERIC(10,2),
    COMMENT VARCHAR(20),
    CONSTRAINT fk_customer_category
    FOREIGN KEY (CUSTOMER_CATEGORY) 
    REFERENCES ORDER_BASE.CUSTOMER (CATEGORY)
);